language: python
sudo: false
env:
  - REQUIREMENTS_TXT=requirements.txt
  - REQUIREMENTS_TXT=requirements-ubuntu-16.04.txt
python:
  - 2.7
# command to install dependencies
install:
  - "pip install ."
  - "pip install mock"
  - "pip install coveralls"
  - "pip install codecov"
  - "pip install -r $REQUIREMENTS_TXT"
  - "pip install smpplib"
# split the test run according to
# http://blog.travis-ci.com/2012-11-28-speeding-up-your-tests-by-parallelizing-them/
#env:
#  - TESTSCRIPT=tests/test_api_system.py
#  - TESTSCRIPT=tests/test_api_token.py
#  - TESTSCRIPT=tests/test_api_users.py
#  - TESTSCRIPT=tests/test_api_validate.py
#  - TESTSCRIPT=tests/test_db_model.py
#  - TESTSCRIPT=tests/test_lib_apps.py
#  - TESTSCRIPT=tests/test_lib_config.py
#  - TESTSCRIPT=tests/test_lib_crypto.py
#  - TESTSCRIPT=tests/test_lib_importotp.py
#  - TESTSCRIPT=tests/test_lib_policy.py
#  - TESTSCRIPT=tests/test_lib_realm.py
#  - TESTSCRIPT=tests/test_lib_resolver.py
#  - TESTSCRIPT=tests/test_lib_tokenclass.py
#  - TESTSCRIPT=tests/test_lib_token.py
#  - TESTSCRIPT=tests/test_lib_tokens_hotp.py
#  - TESTSCRIPT=tests/test_lib_tokens_passwordtoken.py
#  - TESTSCRIPT=tests/test_lib_tokens_totp.py
#  - TESTSCRIPT=tests/test_lib_tokens_yubikey.py
#  - TESTSCRIPT=tests/test_lib_user.py
#  - TESTSCRIPT=tests/test_resolver_realm.py
# command to run tests
#script: "nosetests -v --with-coverage --cover-package=privacyidea $TESTSCRIPT"
script: "nosetests -v --with-coverage --cover-package=privacyidea tests"

after_success: 
    - codecov

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/aeb7493dbe5c478e6c2b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
